animal1=input("What is your favorite animal? ")
building1=input("Name a famous building: ")
color1=input("What is your favorite color? ")
print("Hickory Dickory Dock!")
print("The "+color1+" "+animal1+" ran up the "+building1)
print("\nPlease Change your Input")
animal2=input("Please Change your favorite animal ")
building2=input("Please Change Name a famous building: ")
color2=input("Please Change your favorite color? ")
print("The "+color2+" "+animal2+" ran up the "+building2)